spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/practice
        username: root
        password: shangus
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true
        jwt:
            secret: myVerySecureAndLongJwtSecretKeyForProductionUsemyVerySecureAndLongJwtSecretKeyForProductionUse